// Code generated by goctl. DO NOT EDIT.
package types

type Comment struct {
	ID        string `json:"id"`
	ArticleId string `json:"article_id"`
	Content   string `json:"content"`
	UserId    string `json:"user_id"`
	Nickname  string `json:"nickname"`
	LikeNum   int64  `json:"like_num"`
	ReplyNum  int64  `json:"reply_num"`
	State     string `json:"state"`
	ParentId  string `json:"parent_id"`
	UpdateAt  string `json:"update_at"`
	CreateAt  string `json:"create_at"`
}

type SaveCommentReq struct {
	ArticleId string `json:"article_id"`
	Content   string `json:"content"`
	UserId    string `json:"user_id"`
	Nickname  string `json:"nickname"`
	LikeNum   int64  `json:"like_num"`
	ReplyNum  int64  `json:"reply_num"`
	State     string `json:"state"`
	ParentId  string `json:"parent_id"`
}

type SaveCommentResp struct {
	Message string `json:"message"`
}

type UpdateCommentReq struct {
	Id        string `json:"id"`
	ArticleId string `json:"article_id,optional"`
	Content   string `json:"content,optional"`
	UserId    string `json:"user_id,optional"`
	Nickname  string `json:"nickname,optional"`
	LikeNum   int64  `json:"like_num,optional"`
	ReplyNum  int64  `json:"reply_num,optional"`
	State     string `json:"state,optional"`
	ParentId  string `json:"parent_id,optional"`
}

type UpdateCommentResp struct {
	Message string `json:"message"`
}

type DeleteCommentReq struct {
	Id string `json:"id"`
}

type DeleteCommentResp struct {
	Message string `json:"message"`
}

type FindAllCommentReq struct {
	Id string `json:"id"`
}

type FindAllCommentResp struct {
	List []*Comment `json:"list"`
}

type FindCommentByIdReq struct {
	Id string `form:"id"`
}

type FindCommentByIdResp struct {
	List []*Comment `json:"list"`
}
