// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	comment "article-comment/api/internal/handler/comment"
	"article-comment/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/comment/save",
				Handler: comment.SaveCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/comment/update",
				Handler: comment.UpdateCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/comment/del",
				Handler: comment.DeleteCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/comment/list",
				Handler: comment.FindAllCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/comment/id",
				Handler: comment.FindCommentByIdHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
