// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	test "article-comment/api/internal/handler/test"
	"article-comment/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/get_book",
				Handler: test.GetBookHandler(serverCtx),
			},
		},
		rest.WithPrefix("/userapi/v1"),
	)
}
